<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
    <ProjectReference Include="../../src/Meshline.Cli/Meshline.Cli.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
